In [20]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

from sklearn.metrics import accuracy_score, classification_report

In [21]:
dataset = pd.read_csv('news.csv')

In [22]:
dataset

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [23]:
independent = dataset['text']
dependent = dataset['label']

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size = 0.2, random_state = 10)

In [26]:
vectorizer = CountVectorizer(stop_words='english')

count_x_train = vectorizer.fit_transform(x_train)
count_x_test = vectorizer.transform(x_test)

In [27]:
models = {
    "Naive Bayes": MultinomialNB(),
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=10),
    "Linear SVC": LinearSVC(random_state=10)
}

results = []

for name, model in models.items():
  
    model.fit(count_x_train, y_train)
    

    y_pred = model.predict(count_x_test)
    
    acc = accuracy_score(y_test, y_pred)
    results.append({"Model": name, "Accuracy": acc})
    
    print(f" {name} Accuracy: {acc:.4f}")

summary_df = pd.DataFrame(results).sort_values(by="Accuracy", ascending=False).reset_index(drop=True)

 Naive Bayes Accuracy: 0.8950
 Logistic Regression Accuracy: 0.9274
 Linear SVC Accuracy: 0.8998

D:\anaconda\Lib\site-packages\sklearn\svm\_base.py:1298: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

In [30]:
# Display final ranking table
print("\nMODEL COMPARISON SUMMARY")
display(summary_df)

# Show best model
best_model_name = summary_df.loc[0, "Model"]
best_acc = summary_df.loc[0, "Accuracy"]
print(f"\n Best Performing Model: {best_model_name} with an Accuracy of {best_acc:.4f}")

MODEL COMPARISON SUMMARY

                 Model  Accuracy
0  Logistic Regression  0.927388
1           Linear SVC  0.899763
2          Naive Bayes  0.895028

 Best Performing Model: Logistic Regression with an Accuracy of 0.9274